### ISSUE TITLE
Invalid tokens

### ISSUE THREAD

**Issue by johnnyontheweb** [pieterderycke/Jace#14]
I have formulas like this:
$Load1/(4*$g)
in which "$Load1" and "$g" are variables.

I get "Invalid token "$" detected at position 0" when I try to run Jace with that.
Why "$" is not accepted as part of the variable name?

thanks,
Giovanni

**Comment by pieterderycke** [comment]
Hello Giovanni,

There is no special reason why it is not supported. If needed, I could add support for it in a future version of Jace.NET.

Kind regards,
Pieter

**Comment by johnnyontheweb** [comment]
It would be great to have the characters "$" and "_" as part of the variable name, like in many programming language.

Thanks, regards,
Giovanni

**Comment by johnnyontheweb** [comment]
Currently I see that "_" is not supported as first character of a variable name
