### ISSUE TITLE
Multiple Conditions: IF(var1==1 && var2==2, 1, 2)

### ISSUE THREAD

**Issue by mikec212** [pieterderycke/Jace#16]
Is this supported?

**Comment by johnnyontheweb** [comment]
I have the same problem. I think this is not supported because the "&&" operator is not defined (standing to what is written in the wik, at least). Maybe a custom functions will work in this case?

**Comment by pieterderycke** [comment]
I will look to include support for "and" and "or". I assume this will cover the need?
Jace 0.9 addes improved support for writing custom funtions. The goal is to create a Jace 0.9.1 with a greatly extended list of functions. I also plan to improve the wiki information on the functions

Kind regards,
Pieter

**Comment by pieterderycke** [comment]
I have added support for the 'and' and 'or' operations:
https://github.com/pieterderycke/Jace/commit/196dbec6d70fcdfd9abacfced068377716bae0ee
https://github.com/pieterderycke/Jace/commit/73c8a5e6df69b09eca4ce5aeeba49f8f68979871

**Comment by pieterderycke** [comment]
Released as part of Jace v0.9.1
