### ISSUE TITLE
Simple sum and subtract operation is returning incorrect result.

### ISSUE THREAD

**Issue by pikenikes** [pieterderycke/Jace#23]
The calculus (570.8957 + 114.1791) - (543.75 + 108.75) returns 32.574800000000096 on Jace however it should return 32.5748.

Thanks!

**Comment by jacksondus** [comment]
I'm pretty sure that's just C# trimming off useful information in favor of performance. I would hardly call that trivial difference "incorrect".

**Comment by pieterderycke** [comment]
@jacksondus is correct. This is due to rounding of .NET
