### ISSUE TITLE
.NET Standard Nuget Package

### ISSUE THREAD

**Issue by ordinaryorange** [pieterderycke/Jace#29]
I have a need to run Jace in a .NET Core app.
I could not use the Nuget version as it targets the .NET Framework.
So I checked out the Portable library. I ran Visual Studio Portability plugin tool over this project at it gave a 100% pass for .NET Standard.
Whilst I can use the portable lib in my .NET Core library now, I'd love to be able to link it to a NuGet package so I can receive any future updates.
Is this a feasible thing to do ? Or are there some things about the Portable project I'm not aware of ?

**Comment by pieterderycke** [comment]
I will create a 0.9 version of Jace that will support .Net Standard. So .NET core will become supported

**Comment by pieterderycke** [comment]
The 0.9 is in the Dev branch with support for .NET Standard 1.6
