### ISSUE TITLE
Scientific notation support

### ISSUE THREAD

**Issue by fponta** [pieterderycke/Jace#34]
Is it possible to have support for scientific notation? 
I'd like to be able to write something like
```c#
engine.Build("var1+2.11E-3");
```

At the moment the error message I get is "The syntax of the provided formula is not valid."

Similarly 
```c#
engine.Build("2.11E-3");
```
gives "Unexpected floating point constant "2.11" found."

Thanks

**Comment by pieterderycke** [comment]
support for scientific notation added in the dev branch

**Comment by nikkjazz** [comment]
I'm using JacePxd (0.9.0) from NUGet in VB.NET.  Evaluating strings containing scientific notation throws an error:

Could not evaluate string '(133.6954*1.99840144432528E-15)'
Error details: Unexpected floating point constant "133.6954" found.

Any idea what might be causing this?

**Comment by pieterderycke** [comment]
Would it be possible to try this with the regular Jace.NET (you find the latest version on NuGet). JacePxd is a fork; hence I cannot really give support for that fork.

**Comment by nikkjazz** [comment]
I've struggled to get this installed.  The error I get is:

Error |   | Could not install package 'Jace 0.9.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by nikkjazz** [comment]
Issue with installing Jace 0.9.3 sorted, I was able to get my project running successfully.

Initial testing though suggests a big drop off in performance.  Complex calculations (with several thousands of calls) that are currently executing in c. 14secs in Jace-Pxd (0.9.0) are taking c. 20 secs in Jace 0.9.3.  I'll do some more controlled benchmarks to validate before reporting back.

**Comment by pieterderycke** [comment]
Would it possible for this performance issue to create a dedicated issue? this performance issue has nothing to do with the scientific notation. its for better follow-up

**Comment by nikkjazz** [comment]
> Would it possible for this performance issue to create a dedicated issue? this performance issue has nothing to do with the scientific notation. its for better follow-up

Will do.
