### ISSUE TITLE
Rev to version 1.0?

### ISSUE THREAD

**Issue by KarlZ** [pieterderycke/Jace#42]
I saw from your blog (Pieter) that you plan to rev to 1.0 when you add a few more features. Does it really need to wait for those?
Most people are nervous about using something that has a version number less than 1 (ok.. they're typically nervous for 1 as well, but less so).
This looks like a quality library. I like the test coverage. But I noticed it doesn't have as many downloads as I would expect.
Do you think the number of downloads would increase if it had a version that signals, "This is released"?

**Comment by pieterderycke** [comment]
Hello @KarlZ, that is actually a very good remark. I am already thinking for quite some time how I could increase the downloads of Jace given that its indeed lower than other similar libraries.

And If I would want to release a version 1 in the coming months: are there still features lacking?

**Comment by pieterderycke** [comment]
Jace 1.0 was released 😄
