### ISSUE TITLE
Documentation error about standard function IF 

### ISSUE THREAD

**Issue by jsanjuan2016** [pieterderycke/Jace#46]
There is an error on the documentation related to the standard function IF.
The description of the function and the example provided uses the comma (,) as operator separator. It seems that the valid separator is ;

Therefore the correct information for the IF function must be as follow:
- if(A1; A2; A3) -> GOOD
- if(A1, A2, A3) -> BAD

The example provided must be changed to:
engine.Calculate("if(var1 < var2; 23; 8)", variables);

**Comment by pieterderycke** [comment]
This depends on your culture settings (so on your machine. Try putting Jace in invariant culture mode:

```csharp
CalculationEngine engine = new CalculationEngine(CultureInfo.InvariantCulture);
```
