### ISSUE TITLE
Effiency around functions

### ISSUE THREAD

**Issue by npehrsson** [pieterderycke/Jace#49]
Wouldn't it be more efficient to register the function like this:
> FunctionRegistry.RegisterFunction("sin", (Func<double, double>)Math.Sin, false);`

Instead of

> FunctionRegistry.RegisterFunction("sin", (Func<double, double>)((a) => Math.Sin(a)), false);

Thinking of that it would be one less function call.
But I may be mistaken.

**Comment by pieterderycke** [comment]
yes, you are fully right. It would indeed be an improvement to do so.

**Comment by pieterderycke** [comment]
Done in the dev branch. It will be released as part of Jace 1.0

**Comment by npehrsson** [comment]
Thanks for quick reply
