### ISSUE TITLE
Documentation Does not match Released Master Version

### ISSUE THREAD

**Issue by moizkagdi** [pieterderycke/Jace#52]
Hello, 
(New here on Github. )
I was looking for a calculation engine for my project and yours is very good. However, when trying out the compile-time constant example (image attached) I noticed that the documentation for the same does not match the Master branch released version.
Seems like that feature is still in the dev branch. 

![Annotation 2019-12-31 102117](https://user-images.githubusercontent.com/59376938/71604619-4f707100-2bb7-11ea-8b56-bb3d06971b28.png)

Thought to bring it to your notice. 

Also, I saw that you are incorporating .Net Core as well and planning a release for 1.0 version. Is there an estimate on when the version 1.0 would be released?

Thank you for everything.
Regards,

**Comment by pieterderycke** [comment]
Hello,

The current version of Jace already supports .NET Core.
The 1.0 version of Jace will be released in one of the coming weeks.

regards,
Pieter

**Comment by pieterderycke** [comment]
Jace 1.0 was released. You can also find it on Nuget
