### ISSUE TITLE
Can we make Random overrideable?

### ISSUE THREAD

**Issue by TyrenDe** [pieterderycke/Jace#56]
We built against 0.9.3 and added our own implementation of "random" that is different.  We'd like to keep it. If it were overridable that would be ideal.

**Comment by TyrenDe** [comment]
FYI: You did jump a major version, so I totally understand if you are wanting to leave it alone. It just requires us to do upgrade work for our save files.

**Comment by mrxrsd** [comment]
I don't know if I really understand your question...but why don't you initialize JaceOptions with "DefaultFunctions" = false ?

The only trade-off it is if you use another default function you will need to register it too.

**Comment by TyrenDe** [comment]
Yeah we want all of the default functions. But we had made our own "random" implementation on 0.9.3 (because one didn't exist), and our implementation is different.  So, there is no way for us to use our random, but keep the rest of the default functions.

It's fine, we decided to work around it by renaming ours, and converting existing random calls to use our custom method name.
