### ISSUE TITLE
PEMDAS

### ISSUE THREAD

**Issue by Thokar** [pieterderycke/Jace#81]
Hey

when i calculate 20 / 2 * 5 it gives 50

But Right is 2, because it has to multiply before divide. 

https://www.youtube.com/watch?v=D1eccH1lUKE

**Comment by FabianNitsche** [comment]
I do not get it, even your YouTube video says, 50 is correct... And 50 is correct.
![image](https://github.com/pieterderycke/Jace/assets/26221781/1fc8ea01-034c-4d3c-b5b9-4e4eb92d763c)

**Comment by Thokar** [comment]
Ok sry i was wrong :D
